;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
ManifestDependencies=D:/Ue5.6/UE_5.6/Engine/Content/Localization/Engine/Engine.manifest
ManifestDependencies=D:/Ue5.6/UE_5.6/Engine/Content/Localization/Editor/Editor.manifest
SourcePath=Content/Localization/Game
DestinationPath=Content/Localization/Game
ManifestName=Game.manifest
ArchiveName=Game.archive
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=th
CulturesToGenerate=zh-Hans
CulturesToGenerate=ru-RU
CulturesToGenerate=es-ES
CulturesToGenerate=ja-JP
CulturesToGenerate=ko
CulturesToGenerate=id-ID
CulturesToGenerate=pt-BR
CulturesToGenerate=fr-FR
CulturesToGenerate=de-DE
CulturesToGenerate=pl-PL
CulturesToGenerate=vi-VN
CulturesToGenerate=it-IT

[GatherTextStep0]
CommandletClass=GatherTextFromAssets
IncludePathFilters=Content/FPK/UI/Localization/*
IncludePathFilters=Content/HorrorEngine/*
IncludePathFilters=Content/FPK/UI/*
IncludePathFilters=Content/EUAI/Blueprints/Enemy/*
IncludePathFilters=Content/Game/SFX/Voice_Over/Killer_Game/*
IncludePathFilters=Content/EUAI/Blueprints/Enemy/MascotKillerActor/*
IncludePathFilters=Content/Maps/*
IncludePathFilters=Content/Game/Levels/*
IncludePathFilters=Content/Document/DocTable/*
IncludePathFilters=Content/Document/*
IncludePathFilters=Content/Game/3D_Assets/Props/ControlPanel/*
ExcludePathFilters=Content/Localization/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
ShouldExcludeDerivedClasses=false
ShouldGatherFromEditorOnlyData=false
SkipGatherCache=false

[GatherTextStep1]
CommandletClass=GenerateGatherManifest

[GatherTextStep2]
CommandletClass=GenerateGatherArchive

[GatherTextStep3]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=Game.csv
bConflictReport=true
ConflictReportName=Game_Conflicts.txt

