;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="EaiExample.AiPawn.Location",DevComment="")
+GameplayTagList=(Tag="EaiExample.Ambient.Hunger",DevComment="")
+GameplayTagList=(Tag="EaiExample.Ambient.IsEatingFood",DevComment="")
+GameplayTagList=(Tag="EaiExample.Companion.Order",DevComment="")
+GameplayTagList=(Tag="EaiExample.Companion.RefusingOrder",DevComment="")
+GameplayTagList=(Tag="EaiExample.Enemy.AcceptRadius",DevComment="")
+GameplayTagList=(Tag="EaiExample.Enemy.Ammo",DevComment="")
+GameplayTagList=(Tag="EaiExample.Enemy.DistToPlayer",DevComment="")
+GameplayTagList=(Tag="EaiExample.Enemy.IsSensingPlayer",DevComment="")
+GameplayTagList=(Tag="EaiExample.Enemy.MaxAmmo",DevComment="")
+GameplayTagList=(Tag="EaiExample.Enemy.MeleeAttackDist",DevComment="")
+GameplayTagList=(Tag="EaiExample.Enemy.PlayerLastSeen",DevComment="")
+GameplayTagList=(Tag="EaiExample.Enemy.RangeAttackDist",DevComment="")
+GameplayTagList=(Tag="EaiExample.Enemy.Stunt",DevComment="")
+GameplayTagList=(Tag="EaiExample.Player",DevComment="")
+GameplayTagList=(Tag="EaiExample.Player.HideObj",DevComment="")

